include/itkPhaseCorrelationImageRegistrationMethod.hxx

To address:
itk::PadImageFilter<TInputImage,TOutputImage>::SetPadUpperBound(const itk::Size<VDimension>)' : cannot convert parameter 1 from 'unsigned long [2]' to 'const itk::Size<VDimension>'
with
[
TInputImage=itk::Image<float,2>,
TOutputImage=itk::Image<double,2>,
VDimension=2
]
and
[
VDimension=2
]
No constructor could take the source type, or constructor overload resolution was ambiguous

COMP: unsigned long -> itk::Size conversion on Windows

---

include/itkPhaseCorrelationImageRegistrationMethod.h

...\itkmontage\include\itkphasecorrelationimageregistrationmethod.h(179): error C3861: 'purposeful_error': identifier not found
These errors appear if ITK_FUTURE_LEGACY_REMOVE is turned ON.

Using itkGetConstObjectMacro, fixing errors of the style:

---

include/itkMaxPhaseCorrelationOptimizer.hxx
include/itkPhaseCorrelationImageRegistrationMethod.h
include/itkPhaseCorrelationImageRegistrationMethod.hxx
include/itkPhaseCorrelationOptimizer.h
include/itkPhaseCorrelationOptimizer.hxx
test/CMakeLists.txt
test/itkPhaseCorrelationImageRegistrationMethodTestFiles.cxx

PhaseCorrelationImageRegistrationMethod has a symmetry around the image middle.
So pass fixed and moving images to PhaseCorrelationOptimizer so it can choose
the proper quadrant which minimizes the overall translation.
Also update *Files test to take advantage of modifications, and update its ground truth. Now it is within one pixel.
Closes #20.

BUG: fix huge errors in Tiles test

---

include/itkTileMergeImageFilter.hxx
include/itkTileMontage.h
include/itkTileMontage.hxx
test/itkMontageTestHelper.hxx

Also releases FFT cache and tile memory at earliest possible time.
Closes #47.

ENH: register to adjacent tiles along all dimensions

---

include/itkTileMergeImageFilter.hxx

currentRegion.Crop(reqR) on line 471 causes a change of index
in non-trivial intersections, which caused wrong offset to be used.

BUG: fix incorrect resampling with streaming. Closes #55.

---

.travis.yml

filebin.ca is no longer reliable.

BUG: Use transfer.sh to upload macOS packages.

---

src/itkParseTileConfiguration.cxx

Added additional check to tile configuration parser that removes the carriage return character if it exists at the end of a line. This allows configuration files made in Windows to be read by Mac.

Fixing incorrect Windows config file parsing on Mac

---

include/itkTileMontage.hxx
src/itkParseTileConfiguration.cxx
test/CMakeLists.txt
test/itkMontageTest2D.cxx
test/itkMontageTestHelper.hxx
test/itkPairwiseTestHelper.hxx

Enable more tests to use in-memory approach - it is slightly faster when padding and peak interpolation methods are varied.

More comprehensive testing of registrations filter

---

CMakeLists.txt

To address:
Modules/Core/Common/include/itkNumericTraits.h:1083:36: warning: instantiation of variable 'itk::NumericTraits<std::__1::complex<double> >::Zero' required here, but no definition is available [-Wundefined-var-template]

COMP: complex Zero NumericTrait definition

---

include/itkMaxPhaseCorrelationOptimizer.hxx

Modules/Remote/Montage/include/itkMaxPhaseCorrelationOptimizer.hxx:149:12: warning: declaration of 'dimFactor' shadows a previous local [-Wshadow]
Modules/Remote/Montage/include/itkMaxPhaseCorrelationOptimizer.hxx:146:40: note: shadowed declaration is here
Modules/Remote/Montage/include/itkMaxPhaseCorrelationOptimizer.hxx:149:12: warning: unused variable 'dimFactor' [-Wunused-variable]

COMP: wrong variable was initialized

---

include/itkMaxPhaseCorrelationOptimizer.hxx

Fix unused variable warning.
Fixes:
```
Modules/Remote/Montage/include/itkMaxPhaseCorrelationOptimizer.hxx:305:10:
warning: unused variable 'confidenceFactor' [-Wunused-variable]
```
raised at:
http://testing.cdash.org/viewBuildError.php?type=1&buildid=5914663

COMP: Fix unused variable warning

---

README.rst

The previous badge pointed to the wrong project.
Point to a new Azure Organization / Project created following Azure's
loss of repository access.

Azure configuration update

---

include/itkMaxPhaseCorrelationOptimizer.h
include/itkMaxPhaseCorrelationOptimizer.hxx
include/itkPhaseCorrelationImageRegistrationMethod.h
include/itkPhaseCorrelationImageRegistrationMethod.hxx
include/itkTileMergeImageFilter.h
include/itkTileMergeImageFilter.hxx
include/itkTileMontage.h
include/itkTileMontage.hxx
test/CMakeLists.txt
test/itkInMemoryMontageTestHelper.hxx
test/itkMontageGenericTests.cxx
test/itkMontagePCMTestSynthetic.cxx
test/itkMontageTestHelper.hxx

This makes better use of available processing power, by overlapping different phases of computation: memory-bound, cache-bound (and if tiles are not in memory, IO).

Improve coarse-grained parallelism

---

examples/Montage2D.cxx
examples/RefineMontage2D.cxx
examples/ResampleMontage2D.cxx
test/itkInMemoryMontageTest2D.cxx
test/itkMontagePCMTestFiles.cxx
test/itkMontageTest2D.cxx
test/itkMontageTruthCreator.cxx

When ITK is configured with the following:
- ITK_LEGACY_REMOVE = ON
- ITK_FUTURE_LEGACY_REMOVE = ON
- Module_ITKMontage = ON
Build errors occur with references to older 'C' style enums. The following changes incorporate the new enum class: **FileModeType** and resolves such errors.
Co-Authored-By: Hans Johnson hans-johnson@uiowa.edu

COMP: Change old enum to new enum class definitions

---

test/CMakeLists.txt
test/itkPairwiseTestHelper.hxx

Also enable pair-wise test for all ground truth tests.
Summary results (below) suggest presence of bias in sub-pixel peak estimation:
```text
PeakInterpolation 0 has average translation bias: -0.040 -0.028
PeakInterpolation 1 has average translation bias: -0.035 -0.025
PeakInterpolation 2 has average translation bias: -0.038 -0.027
Average translation error for padding method 2: 0.194
Test #52: itkMontageGroundTruthRun10-129 ..............***Failed    2.33 sec
PeakInterpolation 0 has average translation bias: -0.011 -0.017
PeakInterpolation 1 has average translation bias: -0.009 -0.014
PeakInterpolation 2 has average translation bias: -0.010 -0.016
Average translation error for padding method 2: 0.162
Test #54: itkMontageGroundTruthRunrun2 ................   Passed    1.58 sec …
```

ENH: add calculation of systematic translation bias to pair-wise test

---

include/itkTileMontage.h

This is causing compile errors when used in our own projects (DREAM.3D and ITKImageProcessingPlugin)
Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

Fix compiler error due to use of non enum macro.

---

include/itkPhaseCorrelationOptimizer.h

This gives a much more humane error message.

ENH: add a concept check to make sure we are not instantiated with bool

---

include/itkPhaseCorrelationOptimizer.hxx

Fix variable shadowing and unused variable warnings.
Fixes:
```
Modules/Remote/Montage/include/itkPhaseCorrelationOptimizer.hxx:584:52:
warning: declaration of 'offset' shadows a previous local [-Wshadow]
typename CyclicShiftFilterType::OffsetType offset;
^~~~~~
```
and
```
Modules/Remote/Montage/include/itkPhaseCorrelationOptimizer.hxx:228:28:
warning: unused variable 'complexInput' [-Wunused-variable]
const ComplexImageType * complexInput = static_cast<ComplexImageType
*>(this->GetInput(3));
^~~~~~~~~~~~
```
raised at:
https://open.cdash.org/viewBuildError.php?type=1&buildid=6677445

COMP: Fix variable shadowing and unused variable warnings

---

.github/workflows/build-test-package.yml
examples/CMakeLists.txt
examples/CompleteMontage.cxx

Fixes compile errors of style:
```
M:\Dashboard\ITK\Modules\Remote\Montage\examples\CompleteMontage.cxx(424): error C2666: 'WriteImage': 2 overloads have similar conversions [M:\Dashboard\ITK-build\Modules\Remote\Montage\examples\CompleteMontage.vcxproj]
M:\Dashboard\ITK\Modules\Remote\Montage\examples\CompleteMontage.cxx(49): note: could be 'void WriteImage<itk::Image<ScalarPixelType,2>>(const TImage *,const char *,bool)'
with
[
TImage=itk::Image<ScalarPixelType,2>
]
m:\dashboard\itk\modules\io\imagebase\include\itkImageFileWriter.h(247): note: or       'void itk::WriteImage<itk::Image<ScalarPixelType,2>*>(TImagePointer &&,const std::string &,bool)' [found using argument-dependent lookup]
with
[
TImagePointer=itk::Image<ScalarPixelType,2> *
]
```

COMP: use built-in ReadImage and WriteImage convenience functions

---

examples/CompleteMontage.cxx
examples/RefineMontage.cxx
test/itkInMemoryMontageTestHelper.hxx

Make clang-format more consistent by enforcing semi-colons
at the end of macros.

STYLE: Force semi-colon at end of macros

---

examples/ResampleMontage.cxx

Make clang-format more consistent by enforcing semi-colons
at the end of macros.

STYLE: 2nd attempt to force semi-colon at end of macros

---

test/itkMontageTestHelper.hxx

Fix initializer list lifetime warning.
Fixes:
```
Modules/Remote/Montage/test/itkMontageTestHelper.hxx:248:28: warning:
assignment from temporary initializer_list does not extend the lifetime of the underlying array [-Winit-list-lifetime]
248 |       interpolationMethods = { static_cast<PeakInterpolationType>(peakMethodNumber) };
|       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
raised at:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7491724

COMP: Fix initializer list lifetime warning

---

include/itkPhaseCorrelationImageRegistrationMethod.h

With legacy disabled, the following error is generated on GCC 9.3:
In file included from /home/dzenan/ITKMontage/src/itkPhaseCorrelationImageRegistrationMethod.cxx:18:
/home/dzenan/ITKMontage/include/itkPhaseCorrelationImageRegistrationMethod.h:176:114: error: ‘"Replace itkGetStaticConstMacro(name) with `Self::name`"’ is not a valid template argument for type ‘unsigned int’ because string literals can never be used in this context
176 |   using ComplexConjugateImageType = Image<std::complex<InternalPixelType>, itkGetStaticConstMacro(ImageDimension)>;
|                                                                                                                  ^
/home/dzenan/ITKMontage/include/itkPhaseCorrelationImageRegistrationMethod.h:349:11: error: ‘ComplexConjugateImageType’ does …

COMP: avoiding deprecated itkGetStaticConstMacro

---

CMakeLists.txt

Updates ITKMontage to match the ITK default C++14 standard (see [https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake/ITKInitializeCXXStandard.cmake#L3](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake/ITKInitializeCXXStandard.cmake#L3)). 
Attempting to build ITKMontage with the C++11 standard against an ITK instance built against the C++14 default standard yields a warning and subsequent errors:
```sh
ITK-build-dev/Modules/Core/Common/itkConfigure.h:56:6: warning: #warning "WARNING:  The current project is configured to use a C++ standard version older than the C++ standard used for this build of ITK" [-Wcpp]
56 |     #warning "WARNING:  The current project is configured to use a C++ standard version older than the C++ standard used for this build of ITK" …
```

Default to C++14

---

include/itkNMinimaMaximaImageCalculator.hxx
include/itkPhaseCorrelationImageRegistrationMethod.hxx
include/itkPhaseCorrelationOperator.hxx
include/itkPhaseCorrelationOptimizer.hxx
include/itkTileMergeImageFilter.hxx
include/itkTileMontage.hxx
test/itkMontagePCMTestSynthetic.cxx
test/itkMontageTestHelper.hxx
test/itkPairwiseTestHelper.hxx

COMP: Remove inclusion of .hxx files as headers
The ability to include either .h or .hxx files as
header files required recursively reading the
.h files twice.  The added complexity is
unnecessary, costly, and can confuse static
analysis tools that monitor header guardes (due
to reaching the maximum depth of recursion
limits for nested #ifdefs in checking).

COMP: Remove inclusion of .hxx files as headers

---

include/itkPhaseCorrelationImageRegistrationMethod.hxx
test/itkMontageTestHelper.hxx

This is necessitated by "ENH: Declare converting Point(v) constructors explicit" from Feb 28th:
https://github.com/InsightSoftwareConsortium/ITK/commit/8825834406356a66705437b74c843a54a47c57c3
The first [error message](https://open.cdash.org/viewBuildError.php?buildid=7779138) was:
```
1>m:\dashboard\itk\modules\remote\montage\include\itkPhaseCorrelationImageRegistrationMethod.hxx(251): error C2440: 'initializing': cannot convert from 'itk::Vector<double,2>' to 'itk::Point<double,2>'
1>m:\dashboard\itk\modules\remote\montage\include\itkPhaseCorrelationImageRegistrationMethod.hxx(251): note: Constructor for class 'itk::Point<double,2>' is declared 'explicit'
```

COMP: Update type correctness of point and vector math

---

examples/SimpleMontage.py

Updates the `SimpleMontage.py` example script to reflect `itk.TileMergeImageFilter` type wrapping updates that were introduced in 5b77535871525f917b9cce8d2e6fdbeb3e47fb82.
Resolves issue where the example would fail to instantiate the filter and halt. Tested with RGB input images.
xref https://github.com/InsightSoftwareConsortium/ITKMontage/commit/5b77535871525f917b9cce8d2e6fdbeb3e47fb82

BUG: Update `TileMergeImageFilter` signature in example script

---

include/itkTileMergeImageFilter.hxx
include/itkTileMontage.hxx

M:\Dashboard\ITK\Modules\Remote\Montage\include\itkTileMergeImageFilter.hxx(318,57): warning C4834: discarding return value of function with 'nodiscard' attribute [M:\Dashboard\ITK-build\Modules\Remote\Montage\test\MontageTestDriver.vcxproj]

COMP: Fix discarding return value warning introduced by ITK 5.4

---

CMakeLists.txt
examples/CMakeLists.txt
include/itkPhaseCorrelationImageRegistrationMethod.hxx
include/itkTileMontage.hxx

This can be caused by 0 confidence values, probably due to large homogeneous (all black) regions.
Closes #219.

Avoid appearance of NaN values

---

.github/workflows/build-test-package.yml
test/itkMontagePCMTestSynthetic.cxx

Problem reported here: https://github.com/InsightSoftwareConsortium/ITK/pull/4378#issuecomment-1877085840

COMP: Fix HyperSphereImageSource class name in type macro (was Image)

---

.github/workflows/build-test-package.yml

Upgrade CI testing to use the latest ITK 5.4.0 version and CI configuration.
Committed via https://github.com/asottile/all-repos

ENH: Upgrade CI for ITK 5.4.0
