InsightSoftwareConsortium/ITKMontage

README.rst
=> DOC: Add AFRL contract to Acknowledgemnts

include/itkPhaseCorrelationImageRegistrationMethod.hxx, include/itkPhaseCorrelationOptimizer.hxx, test/itkPhaseCorrelationImageRegistrationMethodTest.cxx
=> More exhaustive synthetic testing

test/CMakeLists.txt, test/itkMockMontageTest.cxx
Content of Tiles.zip should be in directory test/Input/Tiles
This test exposes additional problems of the method
Closes #21.
=> ENH: adding a test with a mini-montage with ground truth

include/itkPhaseCorrelationImageRegistrationMethod.h, include/itkPhaseCorrelationImageRegistrationMethod.hxx, test/itkPhaseCorrelationImageRegistrationMethodTest.cxx
Also improve code style a bit:
* less statements spanning multiple lines
* remove unnecessary empty lines
* remove some useless comments
Closes #13.
=> ENH: support caching of image FFTs

include/itkMaxPhaseCorrelationOptimizer.hxx, include/itkPhaseCorrelationOperator.h, include/itkPhaseCorrelationOperator.hxx, include/itkTileMontage.h, include/itkTileMontage.hxx, test/itkMontageTestHelper.hxx, test/itkMontageTestOMC.cxx, test/itkMontageTestTiles.cxx
We now require ITK master with multi-threading refactored. Commit aa57caf04732f8c0b56f575b65c532e107720e49 (May 15th) or newer.
=> Adding ResampleIntoSingleImage method

include/itkTileMontage.h, include/itkTileMontage.hxx, itk-module.cmake, test/itkMontageTestHelper.hxx, test/itkPhaseCorrelationImageRegistrationMethodTestSynthetic.cxx
=> ENH: allowing filename to be specified instead of providing images

CMakeLists.txt
Update the CMake minimum required version to match the one required by ITK
master.
=> ENH: Update the CMake minimum required version.

include/itkMaxPhaseCorrelationOptimizer.hxx, include/itkNMinimaMaximaImageCalculator.hxx, include/itkPhaseCorrelationImageRegistrationMethod.h, include/itkPhaseCorrelationImageRegistrationMethod.hxx, include/itkPhaseCorrelationOperator.h, include/itkPhaseCorrelationOperator.hxx, include/itkTileMergeImageFilter.hxx, include/itkTileMontage.hxx, itk-module.cmake, test/itkMontagePCMTestSynthetic.cxx
Dependent on [64facb7](https://github.com/InsightSoftwareConsortium/ITK/commit/64facb7b01f01fd63fa606d84d1b3d204381dac6). Closes #43.
=> Proper Butterworth filtering

examples/CMakeLists.txt, examples/Montage2D.cxx, examples/RefineMontage2D.cxx, examples/ResampleMontage2D.cxx, test/itkMockMontageHelper.hxx, test/itkMontageTest2D.cxx, test/itkMontageTestHelper.hxx
Also simplifying the existing combined example
=> Adding refining and resampling examples

include/itkMaxPhaseCorrelationOptimizer.hxx, include/itkPhaseCorrelationImageRegistrationMethod.h, include/itkPhaseCorrelationImageRegistrationMethod.hxx, src/itkParseTileConfiguration.cxx
Let's see whether this fixes CI's package problem.
=> ENH: refactoring code to fix internal compiler error in GCC 4.8

src/itkParseTileConfiguration.cxx
=> COMP: a recent commit in ITK changed include path of double-conversion

include/itkPhaseCorrelationImageRegistrationMethod.h, include/itkPhaseCorrelationImageRegistrationMethod.hxx, include/itkPhaseCorrelationOptimizer.h, include/itkTileMergeImageFilter.h, include/itkTileMergeImageFilter.hxx, include/itkTileMontage.h, include/itkTileMontage.hxx, test/CMakeLists.txt, test/itkMontagePCMTestFiles.cxx, test/itkMontagePCMTestSynthetic.cxx, test/itkMontageTest2D.cxx, test/itkMontageTestHelper.hxx
Closes #81. @joeykleingers can you also test this?
=> Fix crash when setting tiles from memory

test/CMakeLists.txt, test/itkInMemoryMontageTest2D.cxx, test/itkInMemoryMontageTestHelper.hxx, test/itkMontageTestHelper.hxx
This is a squashed version of #87.
=> Joey's comprehensive test of TileMerge filter

include/itkMaxPhaseCorrelationOptimizer.h, include/itkMaxPhaseCorrelationOptimizer.hxx
=> DOC: Fix typos.

include/itkMaxPhaseCorrelationOptimizer.hxx, include/itkPhaseCorrelationImageRegistrationMethod.h, include/itkPhaseCorrelationImageRegistrationMethod.hxx, include/itkPhaseCorrelationOptimizer.h, include/itkTileMontage.h, include/itkTileMontage.hxx, test/CMakeLists.txt, test/itkMontageTest2D.cxx, test/itkMontageTestHelper.hxx
MNML3, MNML5 and S200 tests have visible problems, all the others have only a few pixel difference to Fiji montages.
=> Exposing confidence and propagating it to top level class

include/itkMaxPhaseCorrelationOptimizer.hxx, include/itkTileMontage.hxx, itk-module.cmake, src/itkParseTileConfiguration.cxx, test/CMakeLists.txt, test/itkMontagePCMTestFiles.cxx, test/itkMontageTestHelper.hxx, test/itkPairwiseTestHelper.hxx
The problem: I took spacing from the wrong input. And then I was partly accounting for that error in `OffsetToTransform` method.
=> Fix spacing

examples/Montage2D.cxx, examples/PhaseCorrelationImageRegistration.cxx, examples/RefineMontage2D.cxx, examples/ResampleMontage2D.cxx, include/itkPhaseCorrelationImageRegistrationMethod.hxx, include/itkTileMontage.h, include/itkTileMontage.hxx, test/CMakeLists.txt, test/itkMontageTestHelper.hxx
=> Add global optimization

include/itkMaxPhaseCorrelationOptimizer.h, include/itkMaxPhaseCorrelationOptimizer.hxx, include/itkTileMontage.h, include/itkTileMontage.hxx, test/CMakeLists.txt, test/itkMontageTest2D.cxx, test/itkMontageTestHelper.hxx, test/itkPairwiseTestHelper.hxx
=> Position tolerance

azure-pipelines.yml, examples/PhaseCorrelationImageRegistration.cxx, include/itkMaxPhaseCorrelationOptimizer.hxx, include/itkParseTileConfiguration.h, include/itkPhaseCorrelationImageRegistrationMethod.h, include/itkPhaseCorrelationImageRegistrationMethod.hxx, include/itkTileMergeImageFilter.h, include/itkTileMergeImageFilter.hxx, include/itkTileMontage.h, include/itkTileMontage.hxx, test/CMakeLists.txt, test/itkMontagePCMTestFiles.cxx, test/itkMontagePCMTestSynthetic.cxx, test/itkMontageTest2D.cxx, test/itkMontageTestHelper.hxx, test/itkPairwiseTestHelper.hxx
Closes #114. Closes #95. Closes #76.
=> Crop to overlap and other improvements

test/CMakeLists.txt
This is the version used to generate results in the paper.
=> ENH: reduce number of tiles in 3D ground truth test

.github/workflows/build-test-package.yml, include/itkPhaseCorrelationOptimizer.hxx, setup.py
This PR will update this module with recent changes made to the `ITKModuleTemplate`. These changes include the following.
- Bump ITK version to `v5.1.1` and ITK Python Package version to `5.1.1.post`
- Adding ITK runtime directory in `PATH` for Windows `cxx` build
- Update the supported Python versions
-  New support minimum: `3.6`
-  New supported maximum: `3.9`
- Update `setup.py` to use `itk-core`, `itk-filtering`, `itk-io` `v5.1.1`
- Bumping package version in `setup.py` from `0.6.0` to `0.7.0`
- Fix `clang` formatting errors
Once this branch is merged, a new tag `v0.7.0` will need to be created.
=> ENH: Update GitHub actions

.github/workflows/build-test-package.yml
Maybe we should translate this to [ModuleTemplate](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate).
=> ENH: build examples as part of CI testing

include/itkTileMontage.h, test/CMakeLists.txt
=> ENH: Enable unit tests which are no longer failing

examples/CompleteMontage.cxx, examples/RefineMontage.cxx, examples/ResampleMontage.cxx, include/itkPhaseCorrelationOptimizer.hxx, test/itkMontageTestHelper.hxx, test/itkPairwiseTestHelper.hxx
Ref https://github.com/InsightSoftwareConsortium/ITK/issues/4802
=> COMP: Get ITK_USE_FLOAT_SPACE_PRECISION=ON to compile again

.clang-format, .github/workflows/apply-clang-format.yml, .github/workflows/build-test-package.yml, .github/workflows/clang-format-linter.yml, include/itkNMinimaMaximaImageCalculator.h, include/itkPhaseCorrelationImageRegistrationMethod.h, include/itkPhaseCorrelationOperator.h, include/itkPhaseCorrelationOptimizer.h, include/itkPhaseCorrelationOptimizer.hxx, include/itkTileMergeImageFilter.h, include/itkTileMergeImageFilter.hxx, include/itkTileMontage.h, include/itkTileMontage.hxx, pyproject.toml, test/itkMontagePCMTestSynthetic.cxx
=> General code style and CI update for ITK 5.4.2
